version: '3.8'

services:
  frontend:
    build: ./Frontend
    ports:
      - "3000:3000"
    networks:
      - rustserver
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ./Backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/rust_server

    networks:
      - rustserver
    depends_on:
      - db
    
  db:
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rust_server
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
    networks:
      - rustserver
    restart: unless-stopped

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./Frontend/build:/usr/share/nginx/html:ro
      - ./nginx/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - rustserver
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  rustserver:
    
